### Get all geotags
GET http://localhost:3000/api/geotags
Accept: application/json

###

### Add a new geotag
POST http://localhost:3000/api/geotags
Content-Type: application/json

{
    "name": "TestTag",
    "latitude": 49.01380,
    "longitude": 8.39080,
    "hashtag": "#test"
}

###

### Get a specific geotag by ID
GET http://localhost:3000/api/geotags/13
Accept: application/json

###

### Update a specific geotag by ID
PUT http://localhost:3000/api/geotags/12
Content-Type: application/json

{
    "name": "UpdatedTag",
    "latitude": 49.01400,
    "longitude": 8.39010,
    "hashtag": "#updated"
}

###

### Search for geotags near a location with a keyword
GET http://localhost:3000/api/geotags?latitude=49&longitude=8&searchterm=updated
Accept: application/json

### Delete a specific geotag by ID
DELETE http://localhost:3000/api/geotags/12
Accept: application/json

###